[package]
name = "actix-web-condo-plan-reporter-api"
version = "0.1.0"
authors = ["Aphimuk Yimsukpaitoon <luroman6@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.3"

[dev-dependencies]
actix-rt = "2"
reqwest = "0.11"
tokio = "1"